server:
  port: 8000
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true


#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

spring:
  application:
    name: exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange-service
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  management:
    tracing:
      sampling:
        probability: 1.0
#  zipkin:
#    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs
  swagger-ui:
    url: /exchange-service/v3/api-docs
  override-server-url: true